import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { useApp } from '../context/AppContext';
import { useAuth } from '../context/AuthContext';
import { datasetAPI, reportAPI } from '../api';
import { jsPDF } from 'jspdf';
import { FileText, Download, Database, BarChart3, Shield, Sparkles, Clock, Trash2 } from 'lucide-react';

export default function ReportsPage() {
  const { user } = useAuth();
  const { selectedDatasetId, selectedDataset, selectedCompany, datasets } = useApp();
  const [dashboard, setDashboard] = useState(null);
  const [predictions, setPredictions] = useState([]);
  const [recs, setRecs] = useState([]);
  const [audit, setAudit] = useState(null);
  const [generating, setGenerating] = useState('');
  const [reports, setReports] = useState([]);

  // Fetch existing reports
  useEffect(() => {
    reportAPI.list()
      .then(res => setReports(res.data))
      .catch(() => {});
  }, []);

  // Fetch data for PDF generation
  useEffect(() => {
    if (!selectedDatasetId) return;
    Promise.all([
      datasetAPI.getDashboard(selectedDatasetId).catch(() => ({ data: null })),
      datasetAPI.getPredictions(selectedDatasetId).catch(() => ({ data: [] })),
      datasetAPI.getRecommendations(selectedDatasetId).catch(() => ({ data: [] })),
      datasetAPI.getAudit(selectedDatasetId).catch(() => ({ data: null })),
    ]).then(([d, p, r, a]) => {
      setDashboard(d.data);
      setPredictions(p.data);
      setRecs(r.data);
      setAudit(a.data);
    });
  }, [selectedDatasetId]);

  const generatePDF = async (type) => {
    setGenerating(type);
    const doc = new jsPDF();
    const company = selectedCompany?.name || 'Company';
    const date = new Date().toLocaleDateString();

    doc.setFillColor(16, 20, 25);
    doc.rect(0, 0, 210, 297, 'F');
    doc.setTextColor(224, 226, 234);

    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('CarbonLens AI', 20, 30);
    doc.setFontSize(10);
    doc.setTextColor(194, 198, 214);
    doc.text('Precision ESG Intelligence', 20, 38);

    doc.setDrawColor(66, 71, 84);
    doc.line(20, 45, 190, 45);

    doc.setFontSize(16);
    doc.setTextColor(173, 198, 255);
    const titles = {
      summary: 'Carbon Summary Report',
      detailed: 'Detailed Analytics Report',
      audit: 'Green Audit Report',
    };
    doc.text(titles[type] || 'Report', 20, 58);
    doc.setFontSize(10);
    doc.setTextColor(194, 198, 214);
    doc.text(`${company} — ${selectedDataset?.name} — ${date}`, 20, 66);

    let y = 82;

    if (dashboard) {
      doc.setFontSize(12);
      doc.setTextColor(224, 226, 234);
      doc.text('Key Metrics', 20, y); y += 10;
      doc.setFontSize(10);
      doc.text(`Total Carbon: ${dashboard.total_carbon.toFixed(2)} tCO2e`, 25, y); y += 7;
      doc.text(`Total Energy: ${dashboard.total_energy.toFixed(2)} kWh`, 25, y); y += 7;
      doc.text(`Total Cost: $${dashboard.total_cost.toFixed(2)}`, 25, y); y += 7;
      doc.text(`Sustainability Score: ${dashboard.sustainability_score.toFixed(1)} / 100`, 25, y); y += 14;
    }

    if (type === 'audit' && audit) {
      doc.setFontSize(12);
      doc.setTextColor(224, 226, 234);
      doc.text('Green Audit Results', 20, y); y += 10;
      doc.setFontSize(10);
      doc.text(`Status: ${audit.status} Risk`, 25, y); y += 7;
      doc.text(`Overall Score: ${audit.overall_score} / 100`, 25, y); y += 7;
      doc.text(`Main Issue: ${audit.main_issue}`, 25, y); y += 7;
      doc.text(`Compute Efficiency: ${audit.compute_efficiency}%`, 25, y); y += 7;
      doc.text(`Storage Utilization: ${audit.storage_utilization}%`, 25, y); y += 7;
      doc.text(`Region Efficiency: ${audit.region_efficiency}%`, 25, y); y += 14;
    }

    if (predictions.length > 0) {
      doc.setFontSize(12);
      doc.setTextColor(224, 226, 234);
      doc.text('AI Predictions', 20, y); y += 10;
      doc.setFontSize(10);
      predictions.forEach(p => {
        doc.text(`${p.month_name}: ${p.predicted_carbon.toFixed(2)} tCO2e (${p.trend_direction})`, 25, y);
        y += 7;
      });
      y += 7;
    }

    if (type === 'detailed' && recs.length > 0) {
      doc.setFontSize(12);
      doc.setTextColor(224, 226, 234);
      doc.text('Recommendations', 20, y); y += 10;
      doc.setFontSize(9);
      recs.forEach(r => {
        if (y > 270) { doc.addPage(); y = 20; }
        doc.setTextColor(173, 198, 255);
        doc.text(`[${r.priority}] ${r.title}`, 25, y); y += 6;
        doc.setTextColor(194, 198, 214);
        const lines = doc.splitTextToSize(r.description, 160);
        doc.text(lines, 25, y); y += lines.length * 5 + 4;
      });
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated by CarbonLens AI — ${date}`, 20, 288);

    // Download locally
    doc.save(`CarbonLens_${type}_${company}_${date}.pdf`);

    // Upload the actual generated PDF file to the backend so Admins and other users can download it
    try {
      const pdfBlob = doc.output('blob');
      const file = new File([pdfBlob], `CarbonLens_${type}_${company}_${date}.pdf`, { type: 'application/pdf' });
      await reportAPI.uploadFile(selectedDatasetId, type, file);
      const res = await reportAPI.list();
      setReports(res.data);
    } catch (err) {
      console.error("Failed to upload generated report to the server.", err);
    }

    setTimeout(() => setGenerating(''), 1000);
  };

  const handleDeleteReport = async (id) => {
    try {
      await reportAPI.delete(id);
      const res = await reportAPI.list();
      setReports(res.data);
    } catch {}
  };

  const handleDatasetDownload = async () => {
    if (!selectedDatasetId) return;
    setGenerating('dataset-download');
    try {
      const res = await datasetAPI.download(selectedDatasetId);
      const url = window.URL.createObjectURL(new Blob([res.data], { type: 'text/csv' }));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', selectedDataset?.name || 'dataset.csv');
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
    } catch (err) {
      alert(err.response?.data?.detail || 'Error downloading dataset');
    } finally {
      setGenerating('');
    }
  };

  const hasDataset = selectedDatasetId && datasets.length > 0;

  const reportTypes = [
    {
      type: 'summary', title: 'Carbon Summary Report', icon: BarChart3,
      desc: 'Overview of carbon emissions, energy usage, and costs with key trends.',
      color: 'var(--primary)', available: !!dashboard,
    },
    {
      type: 'detailed', title: 'Detailed Analytics Report', icon: Sparkles,
      desc: 'Full analytics with AI predictions, recommendations, and optimization insights.',
      color: 'var(--tertiary)', available: !!dashboard,
    },
    {
      type: 'audit', title: 'Green Audit Certificate', icon: Shield,
      desc: 'Comprehensive ESG audit report with compliance status and infrastructure health.',
      color: 'var(--secondary)', available: !!audit,
    },
  ];

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} style={{ display: 'flex', flexDirection: 'column', gap: 32 }}>
      <div>
        <span className="section-label">Document Generation</span>
        <h1 style={{ fontSize: '1.75rem', fontWeight: 800, color: 'white', marginTop: 4 }}>
          Reports {selectedCompany ? `— ${selectedCompany.name}` : ''}
        </h1>
        {hasDataset && (
          <p className="section-subtitle">Generate dataset-based PDF reports for {selectedDataset?.name}</p>
        )}
      </div>

      {/* Generate section — only when dataset is selected */}
      {user?.role === 'csp_analyst' && hasDataset && (
        <motion.div className="glass-card" initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }}
          style={{ padding: 24, display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 16 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
            <div style={{
              width: 44, height: 44, borderRadius: 12,
              background: 'rgba(173,198,255,0.12)',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}>
              <Database size={22} color="var(--primary)" />
            </div>
            <div>
              <h3 className="section-title">Source Dataset</h3>
              <p className="section-subtitle">{selectedDataset?.name}</p>
            </div>
          </div>
          <button className="btn-secondary" onClick={handleDatasetDownload} disabled={generating === 'dataset-download'}>
            <Download size={14} />
            {generating === 'dataset-download' ? 'Downloading...' : 'Download CSV'}
          </button>
        </motion.div>
      )}

      {hasDataset ? (
        <div className="grid-3">
          {reportTypes.map((r, i) => {
            const Icon = r.icon;
            return (
              <motion.div key={r.type} className="glass-card"
                initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: i * 0.1 }}
                style={{ padding: 32, display: 'flex', flexDirection: 'column' }}>
                <div style={{
                  width: 48, height: 48, borderRadius: 12,
                  background: `${r.color}15`,
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  marginBottom: 20,
                }}>
                  <Icon size={24} color={r.color} />
                </div>
                <h3 style={{ fontSize: '1rem', fontWeight: 800, color: 'white', marginBottom: 8 }}>{r.title}</h3>
                <p style={{ fontSize: '0.8rem', color: 'var(--on-surface-variant)', lineHeight: 1.6, flex: 1, marginBottom: 20 }}>
                  {r.desc}
                </p>
                <button
                  className={r.available ? 'btn-primary' : 'btn-secondary'}
                  disabled={!r.available || generating === r.type}
                  onClick={() => generatePDF(r.type)}
                  style={{ width: '100%' }}
                >
                  <Download size={14} />
                  {generating === r.type ? 'Generating...' : r.available ? 'Download PDF' : 'No data yet'}
                </button>
              </motion.div>
            );
          })}
        </div>
      ) : (
        <div className="empty-state" style={{ minHeight: '30vh' }}>
          <Database size={64} />
          <h3>No Dataset Selected</h3>
          <p>Select a dataset to generate reports, or view your past reports below.</p>
        </div>
      )}

      {/* Report History */}
      {reports.length > 0 && (
        <motion.div initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.4 }}>
          <h3 className="section-title" style={{ marginBottom: 16 }}>Report History</h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {reports.map((r) => (
              <div key={r.id} className="glass-card" style={{
                padding: '16px 20px', display: 'flex', alignItems: 'center', justifyContent: 'space-between',
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                  <FileText size={20} color="var(--primary)" />
                  <div>
                    <div style={{ fontSize: '0.875rem', fontWeight: 700, color: 'white' }}>{r.title}</div>
                    <div style={{ display: 'flex', gap: 12, marginTop: 4 }}>
                      <span style={{ fontSize: '0.625rem', color: 'var(--on-surface-variant)', display: 'flex', alignItems: 'center', gap: 4 }}>
                        <Clock size={10} />
                        {new Date(r.created_at).toLocaleDateString()}
                      </span>
                      <span className={`badge ${r.report_type === 'audit' ? 'medium' : r.report_type === 'detailed' ? 'low' : 'high'}`}>
                        {r.report_type}
                      </span>
                    </div>
                  </div>
                </div>
                <div style={{ display: 'flex', gap: 8 }}>
                  {r.file_path && (
                    <button onClick={async () => {
                      try {
                        const res = await reportAPI.download(r.id);
                        const url = window.URL.createObjectURL(new Blob([res.data]));
                        const link = document.createElement('a');
                        link.href = url;
                        link.setAttribute('download', r.file_path.split('/').pop() || 'report.pdf');
                        document.body.appendChild(link);
                        link.click();
                      } catch (err) {
                        alert("Error downloading file");
                      }
                    }}
                      style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--primary)', padding: 4 }}>
                      <Download size={14} />
                    </button>
                  )}
                  {user.role !== 'company_user' && (
                    <button onClick={() => handleDeleteReport(r.id)}
                      style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#64748b', padding: 4 }}>
                      <Trash2 size={14} />
                    </button>
                  )}
                </div>
              </div>
            ))}
          </div>
        </motion.div>
      )}

      {/* Analyst File Upload section */}
      {user?.role === 'csp_analyst' && selectedDatasetId && (
        <motion.div className="glass-card" initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} style={{ padding: 24, marginTop: 16 }}>
          <h3 className="section-title" style={{ marginBottom: 16 }}>Upload Custom Report</h3>
          <div style={{ display: 'flex', gap: 16, alignItems: 'center' }}>
            <input 
              type="file" 
              id="report-upload"
              accept=".pdf,.doc,.docx"
              onChange={async (e) => {
                if (!e.target.files[0]) return;
                setGenerating('upload');
                try {
                  await reportAPI.uploadFile(selectedDatasetId, 'detailed', e.target.files[0]);
                  const res = await reportAPI.list();
                  setReports(res.data);
                } catch (err) {
                  alert("Failed to upload report");
                } finally {
                  setGenerating('');
                }
              }}
              style={{ display: 'none' }}
            />
            <label htmlFor="report-upload" className="btn-secondary" style={{ cursor: 'pointer' }}>
              {generating === 'upload' ? 'Uploading...' : 'Select File to Upload'}
            </label>
            <span style={{ fontSize: '0.8rem', color: 'var(--on-surface-variant)' }}>Upload PDF or Word document for CSP Admin</span>
          </div>
        </motion.div>
      )}

      {/* Info */}
      <div className="glass-card" style={{
        padding: 24, display: 'flex', alignItems: 'center', gap: 16,
        background: 'linear-gradient(135deg, rgba(28,32,37,0.7), rgba(38,42,48,0.7))',
        borderLeft: '4px solid var(--primary)',
      }}>
        <FileText size={24} color="var(--primary)" />
        <div>
          <h4 style={{ fontSize: '0.875rem', fontWeight: 700, color: 'white', marginBottom: 4 }}>
            Reports are generated from your uploaded data
          </h4>
          <p style={{ fontSize: '0.75rem', color: 'var(--on-surface-variant)' }}>
            All reports are dynamically created based on the currently selected dataset. No preloaded or demo data is used.
          </p>
        </div>
      </div>
    </motion.div>
  );
}
